<p>
  <a href="<?php echo $this->baseUrl('readers') ?>">Standard view</a>
  | <a href="<?php echo $this->baseUrl('readers/smartquery') ?>">Alternative view</a>
</p>

<?php echo $this->partial('scaffolding/messages.phtml', $this) ?>

<?php echo $this->partial('scaffolding/add-button.phtml', $this) ?>

<?php echo $this->partial('scaffolding/search-form.phtml', $this) ?>

<?php echo $this->partial('scaffolding/list.phtml', $this) ?>